name: YouTube Live Link Check

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:
  workflow_dispatch:      # Allows manual run

jobs:
  gathering_all_IPTV:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yt_dlp 

    - name: Setup fast static FFmpeg
      run: |
        wget -q https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -O ffmpeg.tar.xz
        tar -xf ffmpeg.tar.xz
        FFMPEG_DIR=$(ls -d ffmpeg-*amd64-static)
        sudo cp "$FFMPEG_DIR/ffmpeg" /usr/local/bin/
        sudo cp "$FFMPEG_DIR/ffprobe" /usr/local/bin/
        ffmpeg -version

    - name: Run main script to get all latest links from YouTube
      run: |
        python main.py

    - name: Commit and push YouTube playlist (ytplaylist.m3u)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        git add ytplaylist.m3u
        if git diff --cached --quiet; then
            echo "No changes to ytplaylist.m3u"
        else
            git commit -m "Update YouTube playlist ($(date '+%Y-%m-%d %H:%M:%S'))"
            git push
        fi
