name: Scan Tianjin IP

on:
  schedule:
    - cron: "0 */12 * * *" # 每 12 小时执行一次
  workflow_dispatch: # 允许手动触发

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Run scan script
        run: |
          mkdir -p ip
          php -r '
          const SUBNET_START = "111.162.200.";
          const SUBNET_END = "111.162.207.";
          const PORT = 8686;
          const CONNECT_TIMEOUT = 0.5;
          $ips = [];
          for ($prefix = 200; $prefix <= 207; $prefix++) {
              for ($i = 0; $i <= 255; $i++) {
                  $ip = "111.162.{$prefix}." . $i;
                  $conn = @stream_socket_client("tcp://{$ip}:" . PORT, $errno, $errstr, CONNECT_TIMEOUT);
                  if ($conn) {
                      fclose($conn);
                      $ips[] = $ip;
                  }
              }
          }
          file_put_contents("ip/tianjinip.json", json_encode(["ips" => $ips, "ts" => time()], JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE));
          '

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ip/tianjinip.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Tianjin IP list [skip ci]"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
