name: Scan Tianjin IPs

on:
  schedule:
    - cron: "0 */4 * * *"   # 每4小时执行一次
  workflow_dispatch:        # 允许手动触发

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install tools (nmap, jq, netcat)
        run: |
          sudo apt-get update
          sudo apt-get install -y nmap jq netcat-openbsd

      - name: Scan with nmap (no host discovery)
        run: |
          set -euo pipefail
          # 只看8686开放，跳过主机发现(-Pn)，禁用DNS(-n)，提高速度(-T4)
          nmap -p 8686 --open -Pn -n -T4 111.162.200.0/21 -oG - | \
            awk '/Ports: 8686\/open/ {print $2}' | sort -u > nmap_ips.txt || true
          echo "nmap found: $(wc -l < nmap_ips.txt)"

      - name: Verify with netcat (parallel TCP connect)
        run: |
          set -euo pipefail
          # 生成 111.162.200.0-111.162.207.255 全量 IP 列表
          python3 -c "import ipaddress; [print(str(ip)) for ip in ipaddress.IPv4Network('111.162.200.0/21')]" > all_ips.txt

          # 并行尝试建立TCP连接，开放则输出IP
          grep -E '^[0-9]+\.' all_ips.txt | \
            xargs -r -I{} -P 256 bash -lc 'nc -n -z -w1 {} 8686 2>/dev/null && echo {}' \
            | sort -u > nc_ips.txt

          echo "netcat found: $(wc -l < nc_ips.txt)"

      - name: Merge, build JSON, and save
        run: |
          set -euo pipefail
          mkdir -p IP
          # 合并 nmap 与 nc 结果
          cat nmap_ips.txt nc_ips.txt 2>/dev/null | sort -u > open_ips.txt || true
          TS=$(date +%s)

          # 若为空，生成空数组；否则转为 JSON 数组
          if [ -s open_ips.txt ]; then
            IPS_JSON=$(jq -R -s -c 'split("\n")[:-1]' open_ips.txt)
          else
            IPS_JSON="[]"
          fi

          jq -n --argjson ips "$IPS_JSON" --argjson ts "$TS" \
            '{ips: $ips, ts: $ts}' > ip/tianjinip.json

          echo "Final IP count: $(jq '.ips | length' ip/tianjinip.json)"
          echo "Sample output:"
          cat ip/tianjinip.json

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ip/tianjinip.json
          git commit -m "Update ip/tianjinip.json (automated)" || echo "No changes to commit"
          git push
